---
- name: Home Server
  hosts: all
  roles:
    - role: docker

    - role: nginx
    - role: docker-systemd # Nginx
      container_name: nginx
      container_repository: nginx
      container_volumes:
        - "/etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
        - "/etc/nginx/conf.d:/etc/nginx/conf.d"
        - "/usr/share/nginx/html:/usr/share/nginx/html"
      container_extra_options:
        - "--network host"
    
    - role: jellyfin-setup
    - role: docker-systemd # Jellyfin
      container_name: jellyfin
      container_repository: jellyfin/jellyfin
      container_volumes:
        - "/media:/media"
        - "/srv/jellyfin/config:/config"
        - "/srv/jellyfin/cache:/cache"
      container_extra_options:
        - "--network host"
        - "--device /dev/dri/renderD128:/dev/dri/renderD128"
        - "--device /dev/dri/card0:/dev/dri/card0"
        - "--group-add=109"
        - "--user 1000:1000"

